### ISSUE TITLE
Misc issues

### ISSUE THREAD

**Issue by KristofferC** [Keno/DebuggerFramework.jl#2]
* Variable `key` undefined at:

https://github.com/Keno/DebuggerFramework.jl/blob/dac99279e4873320b76d02a7cf70b1d29e077ac2/src/DebuggerFramework.jl#L296

Triggers when going to eval prompt with text in the repl buffer:

```jl
julia> @enter 1+1
....

About to run: (add_int)(1, 1)
1|debug > a<<`>>ERROR (in the keymap): UndefVarError: key not defined
```

* `process_exception!` function undefined at:
https://github.com/Keno/DebuggerFramework.jl/blob/dac99279e4873320b76d02a7cf70b1d29e077ac2/src/DebuggerFramework.jl#L259

* `display_diagnostic` function undefined at:

https://github.com/Keno/DebuggerFramework.jl/blob/dac99279e4873320b76d02a7cf70b1d29e077ac2/src/DebuggerFramework.jl#L267

* `Suppressed` undefined at:

https://github.com/Keno/DebuggerFramework.jl/blob/dac99279e4873320b76d02a7cf70b1d29e077ac2/src/DebuggerFramework.jl#L17

**Comment by Keno** [comment]
This is addressed
